// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto/email.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmailService_SendForgotPasswordEmail_FullMethodName = "/proto.EmailService/SendForgotPasswordEmail"
	EmailService_SendPaymentDueEmail_FullMethodName     = "/proto.EmailService/SendPaymentDueEmail"
	EmailService_SendPaymentSuccessEmail_FullMethodName = "/proto.EmailService/SendPaymentSuccessEmail"
)

// EmailServiceClient is the client API for EmailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Email Service definition
type EmailServiceClient interface {
	SendForgotPasswordEmail(ctx context.Context, in *SendForgotPasswordEmailRequest, opts ...grpc.CallOption) (*SendForgotPasswordEmailResponse, error)
	SendPaymentDueEmail(ctx context.Context, in *SendPaymentDueEmailRequest, opts ...grpc.CallOption) (*SendPaymentDueEmailResponse, error)
	SendPaymentSuccessEmail(ctx context.Context, in *SendPaymentSuccessEmailRequest, opts ...grpc.CallOption) (*SendPaymentSuccessEmailResponse, error)
}

type emailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailServiceClient(cc grpc.ClientConnInterface) EmailServiceClient {
	return &emailServiceClient{cc}
}

func (c *emailServiceClient) SendForgotPasswordEmail(ctx context.Context, in *SendForgotPasswordEmailRequest, opts ...grpc.CallOption) (*SendForgotPasswordEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendForgotPasswordEmailResponse)
	err := c.cc.Invoke(ctx, EmailService_SendForgotPasswordEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) SendPaymentDueEmail(ctx context.Context, in *SendPaymentDueEmailRequest, opts ...grpc.CallOption) (*SendPaymentDueEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendPaymentDueEmailResponse)
	err := c.cc.Invoke(ctx, EmailService_SendPaymentDueEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) SendPaymentSuccessEmail(ctx context.Context, in *SendPaymentSuccessEmailRequest, opts ...grpc.CallOption) (*SendPaymentSuccessEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendPaymentSuccessEmailResponse)
	err := c.cc.Invoke(ctx, EmailService_SendPaymentSuccessEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailServiceServer is the server API for EmailService service.
// All implementations must embed UnimplementedEmailServiceServer
// for forward compatibility.
//
// Email Service definition
type EmailServiceServer interface {
	SendForgotPasswordEmail(context.Context, *SendForgotPasswordEmailRequest) (*SendForgotPasswordEmailResponse, error)
	SendPaymentDueEmail(context.Context, *SendPaymentDueEmailRequest) (*SendPaymentDueEmailResponse, error)
	SendPaymentSuccessEmail(context.Context, *SendPaymentSuccessEmailRequest) (*SendPaymentSuccessEmailResponse, error)
	mustEmbedUnimplementedEmailServiceServer()
}

// UnimplementedEmailServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmailServiceServer struct{}

func (UnimplementedEmailServiceServer) SendForgotPasswordEmail(context.Context, *SendForgotPasswordEmailRequest) (*SendForgotPasswordEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendForgotPasswordEmail not implemented")
}
func (UnimplementedEmailServiceServer) SendPaymentDueEmail(context.Context, *SendPaymentDueEmailRequest) (*SendPaymentDueEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPaymentDueEmail not implemented")
}
func (UnimplementedEmailServiceServer) SendPaymentSuccessEmail(context.Context, *SendPaymentSuccessEmailRequest) (*SendPaymentSuccessEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPaymentSuccessEmail not implemented")
}
func (UnimplementedEmailServiceServer) mustEmbedUnimplementedEmailServiceServer() {}
func (UnimplementedEmailServiceServer) testEmbeddedByValue()                      {}

// UnsafeEmailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailServiceServer will
// result in compilation errors.
type UnsafeEmailServiceServer interface {
	mustEmbedUnimplementedEmailServiceServer()
}

func RegisterEmailServiceServer(s grpc.ServiceRegistrar, srv EmailServiceServer) {
	// If the following call pancis, it indicates UnimplementedEmailServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmailService_ServiceDesc, srv)
}

func _EmailService_SendForgotPasswordEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendForgotPasswordEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).SendForgotPasswordEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailService_SendForgotPasswordEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).SendForgotPasswordEmail(ctx, req.(*SendForgotPasswordEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_SendPaymentDueEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPaymentDueEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).SendPaymentDueEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailService_SendPaymentDueEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).SendPaymentDueEmail(ctx, req.(*SendPaymentDueEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_SendPaymentSuccessEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPaymentSuccessEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).SendPaymentSuccessEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailService_SendPaymentSuccessEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).SendPaymentSuccessEmail(ctx, req.(*SendPaymentSuccessEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailService_ServiceDesc is the grpc.ServiceDesc for EmailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EmailService",
	HandlerType: (*EmailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendForgotPasswordEmail",
			Handler:    _EmailService_SendForgotPasswordEmail_Handler,
		},
		{
			MethodName: "SendPaymentDueEmail",
			Handler:    _EmailService_SendPaymentDueEmail_Handler,
		},
		{
			MethodName: "SendPaymentSuccessEmail",
			Handler:    _EmailService_SendPaymentSuccessEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/email.proto",
}
